const ERROR_CODE = Object.freeze({
  ACCESS_EXPIRED: 'ACCESS_TOKEN_UNAUTHORIZED_401_1',
  REFRESH_EXPIRED: 'REFRESH_TOKEN_UNAUTHORIZED_401_1',
  USER_NOT_FOUND: 'USER_NOT_FOUND_404_1',
  ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND_404_1',
  PASSWORD_RESET_NOT_FOUND: 'PASSWORD_RESET_NOT_FOUND_404_1',
  EMAIL_DUPLICATE: 'EMAIL_DUPLICATE_409_1',
  STUDENT_NUMBER_DUPLICATE: 'STUDENT_NUMBER_DUPLICATE_409_1',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR_500_1',
  FORBIDDEN_APPLICANT: 'FORBIDDEN_403_1',
  FORBIDDEN_PRESIDENT: 'FORBIDDEN_403_2',
  FILE_NAME_EXTENSION_NOT_FOUND: 'FILE_NAME_EXTENSION_NOT_FOUND_404_1',
  SORT_NOT_FOUND: 'SORT_NOT_FOUND_404_1',
  IMAGE_COUNT_TOO_LARGE: 'IMAGE_COUNT_TOO_LARGE_413_1',
});

export default ERROR_CODE;
